spring.application.name=techgear-backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TechGearStore1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cu hình JWT
# JWT
app.jwt.secret=CHANGE_THIS_TO_A_LONG_SECRET_KEY_AT_LEAST_32_CHARS
app.jwt.expiration-ms=86400000



